#!/bin/bash
# Copyright 2017 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Source this rc script to prepare the environment for interop builds
# This rc script must be used in the root directory of gRPC

export LANG=en_US.UTF-8

# Download Docker images from DockerHub
export DOCKERHUB_ORGANIZATION=grpctesting

mkdir /Users/kbuilder/workspace

git submodule update --init

cp -R ./ /Users/kbuilder/workspace/grpc
cd /Users/kbuilder/workspace/grpc

brew install md5sha1sum

# set xcode version for Obj-C tests
sudo xcode-select -switch /Applications/Xcode_8.2.1.app/Contents/Developer

set +ex  # rvm script is very verbose and exits with errorcode
source $HOME/.rvm/scripts/rvm
set -e  # rvm commands are very verbose
rvm install ruby-2.4
rvm osx-ssl-certs status all
rvm osx-ssl-certs update all
set -ex

# cocoapods
export LANG=en_US.UTF-8
gem install cocoapods
gem install xcpretty
pod repo update  # needed by python

# Set up gRPC-Go and gRPC-Java to test
git clone --recursive https://github.com/grpc/grpc-go ./../grpc-go
git clone --recursive https://github.com/grpc/grpc-java ./../grpc-java

# Set up Docker for Mac
docker-machine create -d virtualbox --virtualbox-share-folder "/Users/kbuilder/workspace:" default
docker-machine env default
eval $(docker-machine env default)
